"""
Application Tracker — Track which jobs you've applied to.

Reads and writes applications.csv in the project root.
Integrates with output folders generated by generator.py.

Usage:
    python tracker.py list                                        # show all tracked applications
    python tracker.py mark <output_folder>                        # mark a job as applied
    python tracker.py status <output_folder> <new_status>         # update application status

Valid statuses: applied, interviewing, offered, rejected, declined
"""

import csv
import glob
import os
import argparse
from datetime import date

APPLICATIONS_CSV = "applications.csv"
VALID_STATUSES = {"applied", "interviewing", "offered", "rejected", "declined"}
FIELDNAMES = ["job_link", "job_title", "company_name", "date_applied", "status", "output_folder", "notes"]

STATUS_EMOJI = {
    "applied": "📤",
    "interviewing": "💬",
    "offered": "🎉",
    "rejected": "❌",
    "declined": "🚫",
}


# ──────────────────────────────────────────────────────────────────────
# CSV HELPERS
# ──────────────────────────────────────────────────────────────────────

def load_applications() -> list[dict]:
    if not os.path.exists(APPLICATIONS_CSV):
        return []
    with open(APPLICATIONS_CSV, mode="r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def save_applications(rows: list[dict]) -> None:
    with open(APPLICATIONS_CSV, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)


def find_job_in_folder(folder: str) -> dict | None:
    """Extract job metadata from the job_description.md in an output folder."""
    matches = glob.glob(os.path.join(folder, "*_job_description.md"))
    if not matches:
        return None

    jd_path = matches[0]
    job_title = "Unknown"
    company_name = "Unknown"
    job_link = ""

    with open(jd_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line.startswith("# ") and " at " in line:
                parts = line[2:].split(" at ", 1)
                job_title = parts[0].strip()
                company_name = parts[1].strip()
            elif line.startswith("**Link:**"):
                job_link = line.replace("**Link:**", "").strip()

    return {"job_title": job_title, "company_name": company_name, "job_link": job_link}


# ──────────────────────────────────────────────────────────────────────
# COMMANDS
# ──────────────────────────────────────────────────────────────────────

def cmd_list() -> None:
    rows = load_applications()
    if not rows:
        print("No applications tracked yet.")
        print(f"   Use: python tracker.py mark <output_folder>")
        return

    print(f"\n{'='*70}")
    print(f"  Applications ({len(rows)} total)")
    print(f"{'='*70}\n")

    for i, row in enumerate(rows, start=1):
        emoji = STATUS_EMOJI.get(row.get("status", ""), "❓")
        status = row.get("status", "unknown").upper()
        print(f"  {i:>2}. {emoji} [{status}]  {row.get('date_applied', '?')}")
        print(f"      {row.get('job_title', '?')} @ {row.get('company_name', '?')}")
        if row.get("notes"):
            print(f"      📝 {row['notes']}")
        print(f"      📁 {row.get('output_folder', '?')}")
        print()

    # Status summary
    from collections import Counter
    counts = Counter(r.get("status", "unknown") for r in rows)
    summary = "  " + "  |  ".join(
        f"{STATUS_EMOJI.get(s, '❓')} {s}: {c}" for s, c in counts.items()
    )
    print(f"{'─'*70}")
    print(summary)
    print(f"{'─'*70}\n")


def cmd_mark(folder: str, notes: str = "") -> None:
    if not os.path.isdir(folder):
        print(f"❌ Folder not found: {folder}")
        return

    job = find_job_in_folder(folder)
    if not job:
        print(f"❌ No job_description.md found in {folder}")
        print(f"   Re-run generator.py to regenerate this output folder.")
        return

    if not job["job_link"]:
        print(f"❌ Could not extract job link from job_description.md")
        return

    rows = load_applications()
    existing_links = {r["job_link"] for r in rows}

    if job["job_link"] in existing_links:
        existing = next(r for r in rows if r["job_link"] == job["job_link"])
        print(f"⚠️  Already tracked: {job['job_title']} @ {job['company_name']}")
        print(f"   Applied: {existing['date_applied']}  Status: {existing['status']}")
        return

    row = {
        "job_link": job["job_link"],
        "job_title": job["job_title"],
        "company_name": job["company_name"],
        "date_applied": date.today().isoformat(),
        "status": "applied",
        "output_folder": folder,
        "notes": notes,
    }
    rows.append(row)
    save_applications(rows)

    print(f"✅ Marked as applied: {job['job_title']} @ {job['company_name']}")
    print(f"   Date: {row['date_applied']}")
    print(f"   Saved to {APPLICATIONS_CSV}")


def cmd_status(folder: str, new_status: str) -> None:
    new_status = new_status.lower()
    if new_status not in VALID_STATUSES:
        print(f"❌ Invalid status: '{new_status}'")
        print(f"   Valid options: {', '.join(sorted(VALID_STATUSES))}")
        return

    if not os.path.isdir(folder):
        print(f"❌ Folder not found: {folder}")
        return

    job = find_job_in_folder(folder)
    if not job or not job["job_link"]:
        print(f"❌ Could not read job info from {folder}")
        return

    rows = load_applications()
    updated = False
    for row in rows:
        if row["job_link"] == job["job_link"]:
            old_status = row["status"]
            row["status"] = new_status
            updated = True
            print(f"✅ Status updated: {job['job_title']} @ {job['company_name']}")
            print(f"   {old_status} → {new_status}")
            break

    if not updated:
        print(f"❌ Job not found in tracker. Mark it first:")
        print(f"   python tracker.py mark {folder}")
        return

    save_applications(rows)


# ──────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Track job applications.")
    subparsers = parser.add_subparsers(dest="command")

    subparsers.add_parser("list", help="List all tracked applications")

    mark_parser = subparsers.add_parser("mark", help="Mark a job as applied")
    mark_parser.add_argument("folder", help="Output folder from generator.py")
    mark_parser.add_argument("--notes", "-n", default="", help="Optional notes")

    status_parser = subparsers.add_parser("status", help="Update application status")
    status_parser.add_argument("folder", help="Output folder from generator.py")
    status_parser.add_argument("status", help=f"New status: {', '.join(sorted(VALID_STATUSES))}")

    args = parser.parse_args()

    if args.command == "list":
        cmd_list()
    elif args.command == "mark":
        cmd_mark(args.folder, getattr(args, "notes", ""))
    elif args.command == "status":
        cmd_status(args.folder, args.status)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
